### ISSUE TITLE
Login problem with generated link

### ISSUE THREAD

**Issue by var-che** [theopensource-company/playrbase#313]
Let's say I wanted to log in and what I got in the mail was:

`http://localhost:13000/api/auth/magic-link?token=eyJhbGciOiJIUzUxMiIsInR4cCI6IkpXVCJ9.eyJleHAiOjE3MDg3MzU0ODMsImlzcyI6InBsYXlyYmF5ZS5hcHAiLCJhdWQiOiJwbGF5cmJhc2UuYXBwOnZlcmlmeS1lbWFpbCIsInN1YiI6ImFkbWluOjR3cGRhOGxrYmsxa3ZhMzI2Yzk1IiwiU0MiOiJhZG1pbiIsImlhdCI6MTcwODczMzY4M30.CH67jumq3Nk2MuK7fc27Mwe6Y4pfNCuhO_mUM893XAssr_RqgpqdDzKdtrV5THNopCUexb4Kbb7aeKG1MclL_Q`

When I want to enter that link, I get an error with 500. 

I found that the problem is in [here](https://github.com/theopensource-company/playrbase/blob/8d52c42b19e013d0f94f126fcaa44bb39ca0f10b/src/app/(api)/api/auth/magic-link/route.ts#L66) because in that link I did not get any `followup` param.

What I did to fix it is I just 
``` javascript 
 const followup = "";
 ```
and it works now.

**Comment by kearfy** [comment]
Thanks! I pushed out a fix
