### ISSUE TITLE
Creating teams does not work

### ISSUE THREAD

**Issue by var-che** [theopensource-company/playrbase#314]
When I go ahead on that popup, name the team and submit, I get the following error:

```
Unhandled Runtime Error
Error: Found admin:4wpda8lkbk1kva326c95 for field `created_by`, with record `team:807udbu4ry2frgy2me4y`, but expected a record<user>
```

Source
src/app/[locale]/(console)/account/teams/page.tsx (147:21) @ async eval

```javascript

  145 | }) => {
  146 |   const result = (async () => {
> 147 |     const [team] = await surreal.query<[Team]>( /* surql */`
      |                   ^
  148 |               CREATE ONLY team CONTENT {
  149 |                   name: $name,
  150 |               };
```

**Comment by kearfy** [comment]
Hey @var-che, admin accounts were an idea we had at first but is a functionality we decided to discontinue. I'm yet to remove it from the codebase however. Using just a normal user account should do the trick 😃
